<?xml version="1.0" encoding="UTF-8"?><testrun name="Test_RestAssert" project="REST_Test" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="core.Test_RestAssert" time="0.041">
    <testcase name="givenUserDoesNotExists_whenUserInfoIsRetrieved_then404IsReceived" classname="core.Test_RestAssert" time="0.041">
      <error>java.lang.IllegalArgumentException: Illegal character in path at index 35: https://api.github.com/users/does't matter&#13;
	at java.net.URI.create(Unknown Source)&#13;
	at org.apache.http.client.methods.HttpGet.&lt;init&gt;(HttpGet.java:69)&#13;
	at core.Test_RestAssert.givenUserDoesNotExists_whenUserInfoIsRetrieved_then404IsReceived(Test_RestAssert.java:28)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.net.URISyntaxException: Illegal character in path at index 35: https://api.github.com/users/does't matter&#13;
	at java.net.URI$Parser.fail(Unknown Source)&#13;
	at java.net.URI$Parser.checkChars(Unknown Source)&#13;
	at java.net.URI$Parser.parseHierarchical(Unknown Source)&#13;
	at java.net.URI$Parser.parse(Unknown Source)&#13;
	at java.net.URI.&lt;init&gt;(Unknown Source)&#13;
	... 26 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
